services:
  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      - REDIS_URL=redis://redis:6379
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app
      - /app/node_modules # Make sure node_modules is NOT mounted
    command: npm run dev

  redis:
    image: redis:7.0-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data
    
volumes:
  redis-data:
  pg-data:

